apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticket-app
build:
  local:
    push: false
  artifacts:
    - image: arturops/ticket-app-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: arturops/ticket-app-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth/deploy.yaml
    - infra/k8s/auth/svc.yaml
    - infra/k8s/auth/mongo-deploy.yaml
    - infra/k8s/auth/mongo-svc.yaml
    - infra/k8s/ingress.yaml
    - infra/k8s/client/deploy.yaml
    - infra/k8s/client/svc.yaml
