apiVersion: v1
kind: Service
metadata:
  labels:
    app: tickets-mongo
  name: tickets-mongo-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: tickets-mongo
status:
  loadBalancer: {}
