apiVersion: v1
kind: Service
metadata:
  labels:
    app: tickets
  name: tickets-svc
spec:
  ports:
    - port: 3006
      protocol: TCP
      targetPort: 3006
  selector:
    app: tickets
  type: ClusterIP
status:
  loadBalancer: {}
