apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: arturops/ticket-app-client
          name: ticket-app-client
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 3000
          resources: {}
status: {}
