apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client-svc
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: client
  type: ClusterIP
status:
  loadBalancer: {}
