apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: arturops/ticket-app-auth
          name: ticket-app-auth
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 3000
          resources:
            limits:
              # image alone is 325 megabytes
              memory: '700M'
              cpu: '500m'
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-svc:27017/auth'
status: {}
