apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-mongo
  name: auth-mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - image: mongo
          name: auth-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: '1000M'
              cpu: '500m'
status: {}
