apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-svc
spec:
  ports:
    - port: 3005
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth
status:
  loadBalancer: {}
